"""Initial schema

Revision ID: 1454edda6380
Revises: 
Create Date: 2026-01-20 14:14:38.587219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1454edda6380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('portion_description', sa.Text(), nullable=False),
    sa.Column('calories_kcal', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_created_at'), 'meal', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_name'), 'meal', ['name'], unique=False)
    op.create_table('meal_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_type_name'), 'meal_type', ['name'], unique=True)
    op.create_table('week_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('week_start_day', sa.Integer(), nullable=False),
    sa.Column('default_week_plan_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_app_config_singleton'),
    sa.ForeignKeyConstraint(['default_week_plan_id'], ['week_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_template_slot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_template_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('meal_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['day_template_id'], ['day_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_type_id'], ['meal_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_template_id', 'position', name='uq_day_template_slot_position')
    )
    op.create_index(op.f('ix_day_template_slot_day_template_id'), 'day_template_slot', ['day_template_id'], unique=False)
    op.create_table('meal_to_meal_type',
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('meal_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_type_id'], ['meal_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_id', 'meal_type_id')
    )
    op.create_table('round_robin_state',
    sa.Column('meal_type_id', sa.UUID(), nullable=False),
    sa.Column('last_meal_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_meal_id'], ['meal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_type_id'], ['meal_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_type_id')
    )
    op.create_table('week_plan_day',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_plan_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('day_template_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_week_plan_day_weekday'),
    sa.ForeignKeyConstraint(['day_template_id'], ['day_template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['week_plan_id'], ['week_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_plan_id', 'weekday', name='uq_week_plan_day_weekday')
    )
    op.create_table('weekly_plan_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_plan_id', sa.UUID(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['week_plan_id'], ['week_plan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plan_instance_week_start_date'), 'weekly_plan_instance', ['week_start_date'], unique=True)
    op.create_table('weekly_plan_instance_day',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_instance_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_template_id', sa.UUID(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['day_template_id'], ['day_template.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weekly_plan_instance_id'], ['weekly_plan_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_plan_instance_id', 'date', name='uq_weekly_plan_instance_day_date')
    )
    op.create_index(op.f('ix_weekly_plan_instance_day_date'), 'weekly_plan_instance_day', ['date'], unique=False)
    op.create_table('weekly_plan_slot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_instance_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('meal_type_id', sa.UUID(), nullable=True),
    sa.Column('meal_id', sa.UUID(), nullable=True),
    sa.Column('completion_status', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("completion_status IS NULL OR completion_status IN ('followed', 'adjusted', 'skipped', 'replaced', 'social')", name='ck_weekly_plan_slot_status'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_type_id'], ['meal_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weekly_plan_instance_id'], ['weekly_plan_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_plan_instance_id', 'date', 'position', name='uq_weekly_plan_slot_position')
    )
    op.create_index(op.f('ix_weekly_plan_slot_date'), 'weekly_plan_slot', ['date'], unique=False)
    op.create_index(op.f('ix_weekly_plan_slot_weekly_plan_instance_id'), 'weekly_plan_slot', ['weekly_plan_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_plan_slot_weekly_plan_instance_id'), table_name='weekly_plan_slot')
    op.drop_index(op.f('ix_weekly_plan_slot_date'), table_name='weekly_plan_slot')
    op.drop_table('weekly_plan_slot')
    op.drop_index(op.f('ix_weekly_plan_instance_day_date'), table_name='weekly_plan_instance_day')
    op.drop_table('weekly_plan_instance_day')
    op.drop_index(op.f('ix_weekly_plan_instance_week_start_date'), table_name='weekly_plan_instance')
    op.drop_table('weekly_plan_instance')
    op.drop_table('week_plan_day')
    op.drop_table('round_robin_state')
    op.drop_table('meal_to_meal_type')
    op.drop_index(op.f('ix_day_template_slot_day_template_id'), table_name='day_template_slot')
    op.drop_table('day_template_slot')
    op.drop_table('app_config')
    op.drop_table('week_plan')
    op.drop_index(op.f('ix_meal_type_name'), table_name='meal_type')
    op.drop_table('meal_type')
    op.drop_index(op.f('ix_meal_name'), table_name='meal')
    op.drop_index(op.f('ix_meal_created_at'), table_name='meal')
    op.drop_table('meal')
    op.drop_table('day_template')
    # ### end Alembic commands ###
